### ISSUE TITLE
‘Key ssd_300_vgg/conv3/conv3_3/weights/Adam_1 not found in checkpoint’ ,someone meet this problem?

### ISSUE THREAD

**Issue by shuxueslpi** [balancap/SSD-Tensorflow#119]
@balancap 
first,I train a model as the way 'Fine-tuning a network trained on ImageNet',a vgg model,and follow the description,first,train with vgg fixed,I training on VOC07 and VOC12,test on VOC07,only get 0.35MAP after 80K steps,than I want to train the complete model ,so I stop the first step train ,and follow this:
`DATASET_DIR=./tfrecords
TRAIN_DIR=./log_finetune/
CHECKPOINT_PATH=./log/model.ckpt-N
python train_ssd_network.py \
    --train_dir=${TRAIN_DIR} \
    --dataset_dir=${DATASET_DIR} \
    --dataset_name=pascalvoc_2007 \
    --dataset_split_name=train \
    --model_name=ssd_300_vgg \
    --checkpoint_path=${CHECKPOINT_PATH} \
    --checkpoint_model_scope=vgg_16 \
    --save_summaries_secs=60 \
    --save_interval_secs=600 \
    --weight_decay=0.0005 \
    --optimizer=adam \
    --learning_rate=0.00001 \
    --learning_rate_decay_factor=0.94 \
    --batch_size=32`
and I receive the error:
Key ssd_300_vgg/conv3/conv3_3/weights/Adam_1 not found in checkpoint

the whole error:
`W tensorflow/core/framework/op_kernel.cc:993] Not found: Key ssd_300_vgg/conv3/conv3_3/weights/Adam not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key ssd_300_vgg/conv4/conv4_3/biases/Adam not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key ssd_300_vgg/conv4/conv4_2/weights/Adam_1 not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key ssd_300_vgg/conv4/conv4_3/biases/Adam_1 not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key ssd_300_vgg/conv2/conv2_2/biases/Adam not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key ssd_300_vgg/conv2/conv2_2/biases/Adam_1 not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key ssd_300_vgg/conv3/conv3_2/biases/Adam_1 not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key ssd_300_vgg/conv3/conv3_1/biases/Adam not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key ssd_300_vgg/conv2/conv2_2/weights/Adam not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key ssd_300_vgg/conv3/conv3_1/biases/Adam_1 not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key ssd_300_vgg/conv4/conv4_1/weights/Adam_1 not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key ssd_300_vgg/conv4/conv4_1/weights/Adam not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key ssd_300_vgg/conv4/conv4_2/weights/Adam not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key ssd_300_vgg/conv3/conv3_3/biases/Adam_1 not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key ssd_300_vgg/conv4/conv4_1/biases/Adam_1 not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key ssd_300_vgg/conv4/conv4_2/biases/Adam_1 not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key ssd_300_vgg/conv4/conv4_1/biases/Adam not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key ssd_300_vgg/conv2/conv2_2/weights/Adam_1 not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key ssd_300_vgg/conv3/conv3_3/weights/Adam_1 not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key ssd_300_vgg/conv4/conv4_2/biases/Adam not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key ssd_300_vgg/conv3/conv3_2/biases/Adam not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key ssd_300_vgg/conv3/conv3_1/weights/Adam_1 not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key ssd_300_vgg/conv3/conv3_1/weights/Adam not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key ssd_300_vgg/conv3/conv3_2/weights/Adam not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key ssd_300_vgg/conv1/conv1_1/weights/Adam_1 not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key ssd_300_vgg/conv3/conv3_3/biases/Adam not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key ssd_300_vgg/conv1/conv1_1/biases/Adam not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key ssd_300_vgg/conv2/conv2_1/biases/Adam not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key ssd_300_vgg/conv3/conv3_2/weights/Adam_1 not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key ssd_300_vgg/conv1/conv1_2/biases/Adam not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key ssd_300_vgg/conv2/conv2_1/weights/Adam not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key ssd_300_vgg/conv1/conv1_1/weights/Adam not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key ssd_300_vgg/conv1/conv1_1/biases/Adam_1 not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key ssd_300_vgg/conv1/conv1_2/weights/Adam_1 not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key ssd_300_vgg/conv4/conv4_3/weights/Adam not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key ssd_300_vgg/conv1/conv1_2/weights/Adam not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key ssd_300_vgg/conv2/conv2_1/weights/Adam_1 not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key ssd_300_vgg/conv5/conv5_1/biases/Adam_1 not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key ssd_300_vgg/conv2/conv2_1/biases/Adam_1 not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key ssd_300_vgg/conv5/conv5_2/weights/Adam not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key ssd_300_vgg/conv1/conv1_2/biases/Adam_1 not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key ssd_300_vgg/conv5/conv5_1/weights/Adam_1 not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key ssd_300_vgg/conv4/conv4_3/weights/Adam_1 not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key ssd_300_vgg/conv5/conv5_1/biases/Adam not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key ssd_300_vgg/conv5/conv5_1/weights/Adam not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key ssd_300_vgg/conv5/conv5_3/weights/Adam not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key ssd_300_vgg/conv5/conv5_2/biases/Adam_1 not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key ssd_300_vgg/conv5/conv5_3/biases/Adam_1 not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key ssd_300_vgg/conv5/conv5_2/biases/Adam not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key ssd_300_vgg/conv5/conv5_3/weights/Adam_1 not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key ssd_300_vgg/conv5/conv5_3/biases/Adam not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key ssd_300_vgg/conv5/conv5_2/weights/Adam_1 not found in checkpoint
`

is there someone meet this problem?
Thanks for your help!

**Comment by shuxueslpi** [comment]
I have fixed this problem,
first,the TRAIN_DIR in the first step train and second step train must not same.
second,when run the second step train,the parameter --checkpoint_model_scope=ssd_300_vgg,not vgg_16

**Comment by seasonyang** [comment]
@shuxueslpi  same problem，use your mathod it had solved！thanks。

**Comment by RoseLii** [comment]
please help me ?
when i run
This is the eval script.
DATASET_DIR=/home/doctorimage/kindlehe/common/dataset/VOC2007/VOCtest_06-Nov-2007/VOCdevkit/VOC2007_tfrecord/
#/home/doctorimage/kindlehe/common/dataset/VOCdevkit/
#../../../../common/dataset/VOC2007/VOCtest_06-Nov-2007/VOCdevkit/
EVAL_DIR=../log_files/log_eval/ # Directory where the results are saved to
CHECKPOINT_PATH=/home/doctorimage/kindlehe/common/models/tfmodlels/SSD/VGG_VOC0712_SSD_300x300_ft_iter_120000/VGG_VOC0712_SSD_300x300_ft_iter_120000.ckpt
#../../../../common/models/tfmodlels/SSD/VGG_VOC0712_SSD_300x300_ft_iter_120000/VGG_VOC0712_SSD_300x300_ft_iter_120000.ckpt
#dataset_name这个参数在代码里面写死了
python3 ../eval_ssd_network.py 
--eval_dir=${EVAL_DIR} 
--dataset_dir=${DATASET_DIR} 
--dataset_name=pascalvoc_2007 
--dataset_split_name=test 
--model_name=ssd_300_vgg 
--checkpoint_path=${CHECKPOINT_PATH} 
--batch_size=1
raise ValueError('No data files found in %s' % (data_sources,))
ValueError: No data files found in /home/y/2T/wangxingli/SSD-Tensorflow/shujuji/VOCtrainval_06-Nov-2007/VOCdevkit/VOC2007/voc_2007_test_*.tfrecord
but i DATASET_DIR is my datasets path,why error

**Comment by geroge-gao** [comment]
@shuxueslpi @seasonyang could you tell me wha't the second step train mean?

**Comment by geroge-gao** [comment]
I use the ssd_300_vgg to train my own dataset,but I meet the same problem

**Comment by geroge-gao** [comment]
this is my command:
python train_ssd_network.py 
--train_dir=F:\Code\Python\ObjectDetection\train 
--dataset_dir=F:\Code\Python\ObjectDetection\tfrecords 
--dataset_name=tf_hand 
--dataset_split_name=train 
--model_name=ssd_300_vgg
--checkpoint_path=F:\Code\Python\ObjectDetection\SSD-Tensorflow\checkpoints\ssd_300_vgg.ckpt 
--checkpoint_model_scope=ssd_300_vgg 
--save_summaries_secs=60 
--save_interval_secs=600 
--weight_decay=0.0005 
--optimizer=adam 
--learning_rate=0.001 
--learning_rate_decay_factor=0.94 
--batch_size=16
