### ISSUE TITLE
How is the fps?

### ISSUE THREAD

**Issue by shesung** [balancap/SSD-Tensorflow#12]
The readme didn't mention the fps. Is it slower or faster than the original caffe inplementation?

**Comment by balancap** [comment]
I still have to implement a simple script for benchmarking the implementation.
My intuition is that it should follow usual benchmarks on TF vs Caffe. TF is usually a bit slower that pure C++ Caffe implementation.

**Comment by jtn-ms** [comment]
when I tried the original caffe code on ubuntu with gtx970, cuda 8.0, the fps was more than 30. But I tried the tensorflow code on windows 8.1, the fps was just 1 for gpu, 0.3 for cpu. If tensorflow is this much slower than caffe for everything, how can it be used in practical?
