### ISSUE TITLE
How Can I find classes label human read text?

### ISSUE THREAD

**Issue by jinfagang** [balancap/SSD-Tensorflow#13]
I successfully predicted an image, but just got index rather than human read txts, I think it's more proper to write names label text on image, but I cannot find it. Should author consider add it into repo?

**Comment by jinfagang** [comment]
OK, I find that, thanks for this genius work!

**Comment by RitwikGopi** [comment]
@jinfagang 
Maybe I am dumb or just lazy. I have been trying to figure out the same thing. If you don't mind can you tell me where to find it?
