### ISSUE TITLE
routing problem

### ISSUE THREAD

**Issue by RoseLii** [balancap/SSD-Tensorflow#136]
您好，请问我在运行
EVAL_DIR=./logs/
CHECKPOINT_PATH=./checkpoints/VGG_VOC0712_SSD_300x300_ft_iter_120000.ckpt
python eval_ssd_network.py \
    --eval_dir=${EVAL_DIR} \
    --dataset_dir=${DATASET_DIR} \
    --dataset_name=pascalvoc_2007 \
    --dataset_split_name=test \
    --model_name=ssd_300_vgg \
    --checkpoint_path=${CHECKPOINT_PATH} \
    --batch_size=1
我将DATASET_DIR设置成我的数据集的路径，但是还是报错
raise ValueError('No data files found in %s' % (data_sources,))
ValueError: No data files found in /home/y/2T/wangxingli/SSD-Tensorflow/shujuji/VOCtrainval_06-Nov-2007/VOCdevkit/VOC2007/voc_2007_test_*.tfrecord
请问这个路径到底是啥。

**Comment by raymondchua** [comment]
How did you solve this? I am facing the same issue.

**Comment by ManiroXi** [comment]
@raymondchua same error +1

**Comment by ManiroXi** [comment]
@raymondchua It seems that the 'voc_2007_test_*.tfrecord' can not be found. Make sure "voc_2007_test_*.tfrecord" is in your dataset_dir.

**Comment by manutom** [comment]
run cthe dataset conversion script once again. It worked for me
