### ISSUE TITLE
What is anchor_sizes ?

### ISSUE THREAD

**Issue by nsknsl** [balancap/SSD-Tensorflow#14]
in SSDNet():
        anchor_sizes=[(21., 45.),
                      (45., 99.),
                      (99., 153.),
                      (153., 207.),
                      (207., 261.),
                      (261., 315.)]
what is anchor_sizes mean? Can not find something related to this in paper.
I think this must have some relations with the scale (Sk) in paper. What's the relationship?
thank you!

**Comment by yjmade** [comment]
I bet it means the size of each scale on feature layer 4,7,8,9,10,11

**Comment by balancap** [comment]
Exactly, it corresponds to `min` and `max` sizes (in pixels) of each feature layers. Basically, just the scale `s_k` time the size of the input image. 
I want to remove this hard-coded list and it into FLAGS at some point.

**Comment by nlngh** [comment]
In the paper, there is only one Sk per layer. For scale of 0.15, it would correspond to 45pixels with input image shape of 300. For the first feature map you have (21, 45), can you explain why do use 21pixels here?

I am trying to implement this for another architecture with different input image size and this part is a bit obscure to me.

Thanks

**Comment by xbcReal** [comment]
@nurlano hi,I have the same question as you did,and I also don't understand what does 21 stand for in the size(21,45),have you sloved this ?Or can you explain more detaily @balancap 
thanks so much.

**Comment by gloomyfish1998** [comment]
i read the paper and could not find any explain on this, i guess, it is only experience value from practice with start with value 21, could someone can explain this reasonable more
