### ISSUE TITLE
Unable to decode bytes as JPEG, PNG, GIF, or BMP

### ISSUE THREAD

**Issue by seul1993** [balancap/SSD-Tensorflow#147]
I am trying to train the SSD model on my own dataset. I organize my data in the PascalVoc way: my images are in the JPEGImages directory, and the label file is in the Annotations directory. I turn the data into tfrecords using the tf_convert_data.py file and it goes smoothly. However, during training, I meet this error:INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.InvalidArgumentError'>, assertion failed: [Unable to decode bytes as JPEG, PNG, GI F, or BMP]. I have checked that all my images are JPEG images. Can someone be so kind to help me with this problem?

**Comment by wgshun** [comment]
Hi, i also have this problem, can you tell me how did you solve it? Thanks.

**Comment by wgshun** [comment]
@seul1993
