### ISSUE TITLE
Resource exhaustion when loading global variables in SSD_notebook

### ISSUE THREAD

**Issue by Elizabethcase** [balancap/SSD-Tensorflow#157]
Hey,

Getting

```
ResourceExhaustedError: OOM when allocating tensor with shape[3,3,512,512]
	 [[Node: ssd_300_vgg/conv5/conv5_1/weights/Initializer/random_uniform/RandomUniform = RandomUniform[T=DT_INT32, _class=["loc:@ssd_300_vgg/conv5/conv5_1/weights"], dtype=DT_FLOAT, seed=0, seed2=0, _device="/job:localhost/replica:0/task:0/gpu:0"](ssd_300_vgg/conv5/conv5_1/weights/Initializer/random_uniform/shape)]]

Caused by op 'ssd_300_vgg/conv5/conv5_1/weights/Initializer/random_uniform/RandomUniform', defined at:
  File "/home/ubuntu/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)

```
When I run 

`isess.run(tf.global_variables_initializer())`

This was working recently; any idea what's going on? 

Best,
Elizabeth

**Comment by 3born** [comment]
Try restarting the kernel in your notebook - I've had similar experiences with Jupyter slowly eating up GPU memory. You can run e.g. `nvidia-smi` to see if you have any unknown processes allocating a lot of GPU resources.

**Comment by Elizabethcase** [comment]
Thanks -- weirdly, restarting the kernel didn't do anything immediately, nor did restarting the aws instance, but waiting overnight did.
