### ISSUE TITLE
global_step/sec=0

### ISSUE THREAD

**Issue by ghost** [balancap/SSD-Tensorflow#162]
I run SDC-Vehicle-Detection (https://github.com/balancap/SDC-Vehicle-Detection) with widerface dataset for face detection. after creating tfrecords and write train command i got this :

INFO: tensorflow: starting Sessions
INFO: tensorflow: starting Queues
INFO: tensorflow: global_step/sec : 0
INFO: tensorflow: global_step/sec : 0
INFO: tensorflow: global_step/sec : 0.0172539
INFO: tensorflow: global_step/sec : 0
INFO: tensorflow: global_step/sec : 0
INFO: tensorflow: global_step/sec : 0.0167292
....
Is there any problem? where is loss? Is the network training wrong?

**Comment by billyceline** [comment]
Did you solve this problem? This drives me crazy.
