### ISSUE TITLE
Name: <unknown>, Feature: image/channels (data type: int64) is required but could not be found.

### ISSUE THREAD

**Issue by geroge-gao** [balancap/SSD-Tensorflow#168]
when I try to train my own dataset,there happends some error.
this is my command
`python train_ssd_network.py --train_dir=F:\Code\Python\ObjectDetection\train --dataset_dir=F:\Code\Python\ObjectDetection\tfrecords --dataset_name=tf_hand --dataset_split_name=train --model_name=ssd_300_vgg --checkpoint_path=F:\Code\Python\ObjectDetection\SSD-Tensorflow\checkpoints\ssd_300_vgg.ckpt --checkpoint_model_scope=ssd_300_vgg --checkpoint_exclude_scopes=ssd_300_vgg/conv6,ssd_300_vgg/conv7,ssd_300_vgg/block8,ssd_300_vgg/block9,ssd_300_vgg/block10,ssd_300_vgg/block11,ssd_300_vgg/block4_box,ssd_300_vgg/block7_box,ssd_300_vgg/block8_box,ssd_300_vgg/block9_box,ssd_300_vgg/block10_box,ssd_300_vgg/block11_box --trainable_scopes=ssd_300_vgg/conv6,ssd_300_vgg/conv7,ssd_300_vgg/block8,ssd_300_vgg/block9,ssd_300_vgg/block10,ssd_300_vgg/block11,ssd_300_vgg/block4_box,ssd_300_vgg/block7_box,ssd_300_vgg/block8_box,ssd_300_vgg/block9_box,ssd_300_vgg/block10_box,ssd_300_vgg/block11_box --save_summaries_secs=60 --save_interval_secs=600 --weight_decay=0.0005 --optimizer=adam --learning_rate=0.001 --learning_rate_decay_factor=0.94 --batch_size=8
`
the error message is
`2017-11-23 20:47:25.856211: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\framework\op_kernel.cc:1192] Invalid argument: Name: <unknown>, Feature: image/channels (data type: int64) is required but could not be found.
2017-11-23 20:47:25.856252: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\framework\op_kernel.cc:1192] Invalid argument: Name: <unknown>, Feature: image/channels (data type: int64) is required but could not be found.
INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.InvalidArgumentError'>, Name: <unknown>, Feature: image/channels (data type: int64) is required but could not be found.
         [[Node: tf_hand_data_provider/ParseSingleExample/ParseExample/ParseExample = ParseExample[Ndense=6, Nsparse=7, Tdense=[DT_INT64, DT_STRING, DT_STRING, DT_INT64, DT_INT64, DT_INT64], dense_shapes=[[1], [], [], [1], [3], [1]], sparse_types=[DT_INT64, DT_INT64, DT_INT64, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](tf_hand_data_provider/ParseSingleExample/ExpandDims, tf_hand_data_provider/ParseSingleExample/ParseExample/ParseExample/names, tf_hand_data_provider/ParseSingleExample/ParseExample/ParseExample/sparse_keys_0, tf_hand_data_provider/ParseSingleExample/ParseExample/ParseExample/sparse_keys_1, tf_hand_data_provider/ParseSingleExample/ParseExample/ParseExample/sparse_keys_2, tf_hand_data_provider/ParseSingleExample/ParseExample/ParseExample/sparse_keys_3, tf_hand_data_provider/ParseSingleExample/ParseExample/ParseExample/sparse_keys_4, tf_hand_data_provider/ParseSingleExample/ParseExample/ParseExample/sparse_keys_5, tf_hand_data_provider/ParseSingleExample/ParseExample/ParseExample/sparse_keys_6, tf_hand_data_provider/ParseSingleExample/ParseExample/ParseExample/dense_keys_0, tf_hand_data_provider/ParseSingleExample/ParseExample/ParseExample/dense_keys_1, tf_hand_data_provider/ParseSingleExample/ParseExample/ParseExample/dense_keys_2, tf_hand_data_provider/ParseSingleExample/ParseExample/ParseExample/dense_keys_3, tf_hand_data_provider/ParseSingleExample/ParseExample/ParseExample/dense_keys_4, tf_hand_data_provider/ParseSingleExample/ParseExample/ParseExample/dense_keys_5, tf_hand_data_provider/ParseSingleExample/ParseExample/Const, tf_hand_data_provider/ParseSingleExample/ParseExample/Reshape, tf_hand_data_provider/ParseSingleExample/ParseExample/Reshape_1, tf_hand_data_provider/ParseSingleExample/ParseExample/Const, tf_hand_data_provider/ParseSingleExample/ParseExample/Const, tf_hand_data_provider/ParseSingleExample/ParseExample/Const)]]2017-11-23 20:47:25.856250: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\framework\op_kernel.cc:1192] Invalid argument: Name: <unknown>, Feature: image/channels (data type: int64) is required but could not be found.

2017-11-23 20:47:25.856537: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\framework\op_kernel.cc:1192] Invalid argument: Name: <unknown>, Feature: image/channels (data type: int64) is required but could not be found.
2017-11-23 20:47:25.856908: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\kernels\queue_base.cc:303] _5_prefetch_queue/fifo_queue: Skipping cancelled dequeue attempt with queue not closed
2017-11-23 20:47:25.878346: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\framework\op_kernel.cc:1192] Invalid argument: Name: <unknown>, Feature: image/channels (data type: int64) is required but could not be found.
INFO:tensorflow:Caught OutOfRangeError. Stopping Training.
INFO:tensorflow:Finished training! Saving model to disk.
Traceback (most recent call last):
  File "train_ssd_network.py", line 390, in <module>
    tf.app.run()
  File "D:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "train_ssd_network.py", line 386, in main
    sync_optimizer=None)
  File "D:\Program Files\Anaconda3\lib\site-packages\tensorflow\contrib\slim\python\slim\learning.py", line 775, in train
    sv.stop(threads, close_summary_writer=True)
  File "D:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\training\supervisor.py", line 792, in stop
    stop_grace_period_secs=self._stop_grace_secs)
  File "D:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\training\coordinator.py", line 389, in join
    six.reraise(*self._exc_info_to_raise)
  File "D:\Program Files\Anaconda3\lib\site-packages\six.py", line 686, in reraise
    raise value
  File "D:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\training\queue_runner_impl.py", line 238, in _run
    enqueue_callable()
  File "D:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1231, in _single_operation_run
    target_list_as_strings, status, None)
  File "D:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Name: <unknown>, Feature: image/channels (data type: int64) is required but could not be found.
         [[Node: tf_hand_data_provider/ParseSingleExample/ParseExample/ParseExample = ParseExample[Ndense=6, Nsparse=7, Tdense=[DT_INT64, DT_STRING, DT_STRING, DT_INT64, DT_INT64, DT_INT64], dense_shapes=[[1], [], [], [1], [3], [1]], sparse_types=[DT_INT64, DT_INT64, DT_INT64, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](tf_hand_data_provider/ParseSingleExample/ExpandDims, tf_hand_data_provider/ParseSingleExample/ParseExample/ParseExample/names, tf_hand_data_provider/ParseSingleExample/ParseExample/ParseExample/sparse_keys_0, tf_hand_data_provider/ParseSingleExample/ParseExample/ParseExample/sparse_keys_1, tf_hand_data_provider/ParseSingleExample/ParseExample/ParseExample/sparse_keys_2, tf_hand_data_provider/ParseSingleExample/ParseExample/ParseExample/sparse_keys_3, tf_hand_data_provider/ParseSingleExample/ParseExample/ParseExample/sparse_keys_4, tf_hand_data_provider/ParseSingleExample/ParseExample/ParseExample/sparse_keys_5, tf_hand_data_provider/ParseSingleExample/ParseExample/ParseExample/sparse_keys_6, tf_hand_data_provider/ParseSingleExample/ParseExample/ParseExample/dense_keys_0, tf_hand_data_provider/ParseSingleExample/ParseExample/ParseExample/dense_keys_1, tf_hand_data_provider/ParseSingleExample/ParseExample/ParseExample/dense_keys_2, tf_hand_data_provider/ParseSingleExample/ParseExample/ParseExample/dense_keys_3, tf_hand_data_provider/ParseSingleExample/ParseExample/ParseExample/dense_keys_4, tf_hand_data_provider/ParseSingleExample/ParseExample/ParseExample/dense_keys_5, tf_hand_data_provider/ParseSingleExample/ParseExample/Const, tf_hand_data_provider/ParseSingleExample/ParseExample/Reshape, tf_hand_data_provider/ParseSingleExample/ParseExample/Reshape_1, tf_hand_data_provider/ParseSingleExample/ParseExample/Const, tf_hand_data_provider/ParseSingleExample/ParseExample/Const, tf_hand_data_provider/ParseSingleExample/ParseExample/Const)]]`

**Comment by estathop** [comment]
what was the problem of this ? I dealt with something similar

**Comment by mrluin** [comment]
perhaps the features you defined when pares single_example has something wrong, i also have this issue because define features 'lable' but parse features 'label' so it cant get feature lable

**Comment by angleflower** [comment]
Have you solved it? I also have a problem

**Comment by naf140230** [comment]
I have a similar problem. It looks like this:

```
InvalidArgumentError                      Traceback (most recent call last)
/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py in _do_call(self, fn, *args)
   1333     try:
-> 1334       return fn(*args)
   1335     except errors.OpError as e:

/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py in _run_fn(feed_dict, fetch_list, target_list, options, run_metadata)
   1318       return self._call_tf_sessionrun(
-> 1319           options, feed_dict, fetch_list, target_list, run_metadata)
   1320 

/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py in _call_tf_sessionrun(self, options, feed_dict, fetch_list, target_list, run_metadata)
   1406         self._session, options, feed_dict, fetch_list, target_list,
-> 1407         run_metadata)
   1408 

InvalidArgumentError: Feature: channels (data type: int64) is required but could not be found.
	 [[{{node ParseSingleExample/ParseSingleExample}}]]
	 [[{{node IteratorGetNext}}]]

During handling of the above exception, another exception occurred:

InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-2-2aec61f13482> in <module>
     20         try:
     21             #if num_recs>=2*nrecs: break
---> 22             b=sess.run(batch)
     23             if images is None:
     24                 images=b[0]

/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py in run(self, fetches, feed_dict, options, run_metadata)
    927     try:
    928       result = self._run(None, fetches, feed_dict, options_ptr,
--> 929                          run_metadata_ptr)
    930       if run_metadata:
    931         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py in _run(self, handle, fetches, feed_dict, options, run_metadata)
   1150     if final_fetches or final_targets or (handle and feed_dict_tensor):
   1151       results = self._do_run(handle, final_targets, final_fetches,
-> 1152                              feed_dict_tensor, options, run_metadata)
   1153     else:
   1154       results = []

/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py in _do_run(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)
   1326     if handle is None:
   1327       return self._do_call(_run_fn, feeds, fetches, targets, options,
-> 1328                            run_metadata)
   1329     else:
   1330       return self._do_call(_prun_fn, handle, feeds, fetches)

/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py in _do_call(self, fn, *args)
   1346           pass
   1347       message = error_interpolation.interpolate(message, self._graph)
-> 1348       raise type(e)(node_def, op, message)
   1349 
   1350   def _extend_graph(self):

InvalidArgumentError: Feature: channels (data type: int64) is required but could not be found.
	 [[{{node ParseSingleExample/ParseSingleExample}}]]
	 [[node IteratorGetNext (defined at <ipython-input-2-2aec61f13482>:10) ]]
```
In my case, I think I might know the answer. I now have have multiple images with different numbers of channels. It might be throwing off my code to see what the images look like. Does anyone know if that might be the case?
