### ISSUE TITLE
Train on my own data set

### ISSUE THREAD

**Issue by yyjFish** [balancap/SSD-Tensorflow#17]
：）   

I have downloaded vgg_16.ckpt from [download.tensorflow.org/models/vgg_16_2016_08_28.tar.gz](url)

and unzip it on the folder "._/checkpoints_"

----------------------------------------------------------------------------------------------------------------------
### Input：

`DATASET_DIR=./tfrecords`
`TRAIN_DIR=./logs/`
`CHECKPOINT_PATH=./checkpoints/vgg_16.ckpt`
`python train_ssd_network.py \`
`    --train_dir=${TRAIN_DIR} \`
`    --dataset_dir=${DATASET_DIR} \`
`    --dataset_name=pascalvoc_2007 \`
`    --dataset_split_name=train \`
`    --model_name=ssd_300_vgg \`
`    --checkpoint_path=${CHECKPOINT_PATH} \`
`    --checkpoint_exclude_scopes=ssd_300_vgg/block4_box,ssd_300_vgg/block7_box,ssd_300_vgg/block8_box,ssd_300_vgg/block9_box,ssd_300_vgg/block10_box,ssd_300_vgg/block11_box \`
`    --save_summaries_secs=60 \`
`    --save_interval_secs=600 \`
`    --weight_decay=0.00001 \`
`    --optimizer=rmsprop \`
`    --learning_rate=0.0001 \`
`    --batch_size=32`

-------------------------------------------------------------------------------------------------
### Result:

`NotFoundError (see above for traceback): Tensor name "ssd_300_vgg/block10/conv1x1/biases" not found in checkpoint files ./checkpoints/vgg_16.ckpt`

emmmm.....   How to solve this problem？ T_T

Thank you！：）

**Comment by petrama** [comment]
I was having a same problem, then I used inspect_checkpoint.py script (https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/tools/inspect_checkpoint.py) to inspect it.

You have to exclude tensors that aren't in checkpoint with --checkpoint_exclude_scopes
My script for training is like this:

DATASET_DIR=/home/pmarce/datasets/VOCdevkit/tfrecords
TRAIN_DIR=./logs/
CHECKPOINT_PATH=./checkpoints/vgg_16.ckpt
python3 train_ssd_network.py \
    --train_dir=${TRAIN_DIR} \
    --dataset_dir=${DATASET_DIR} \
    --dataset_name=pascalvoc_2007 \
    --dataset_split_name=train \
    --model_name=ssd_300_vgg \
    --checkpoint_path=${CHECKPOINT_PATH} \
    --checkpoint_exclude_scopes=ssd_300_vgg/block4_box,ssd_300_vgg/block7_box,ssd_300_vgg/block8_box,ssd_300_vgg/block9_box,ssd_300_vgg/block10_box,ssd_300_vgg/block11_box,ssd_300_vgg/block8,ssd_300_vgg/block9,ssd_300_vgg/block10,ssd_300_vgg/block11,ssd_300_vgg/conv6,ssd_300_vgg/conv7\
    --save_summaries_secs=60 \
    --save_summaries_secs=60 \
    --save_interval_secs=600 \
    --weight_decay=0.00001 \
    --optimizer=adam \
    --learning_rate=0.0001 \
    --batch_size=8

Also I realized there is inconsistency with names.

I added this in tf_utils.py in function get_init_function right after for loop

 def name_in_checkpoint(var):
        if 'ssd_300_vgg' in var.op.name:
            return var.op.name.replace('ssd_300_vgg','vgg_16')

variables_to_restore = {name_in_checkpoint(var): var for var in variables_to_restore}

**Comment by yyjFish** [comment]
@petrama   wow,  thanks a lot!!!   It works~~~

emmmm......  However ...

The GPU memory of my laptop is not enough

-----------------------------------------------------------------------------------------------------------
name: GeForce GTX 950M
major: 5 minor: 0 memoryClockRate (GHz) 1.124
pciBusID 0000:01:00.0
Total memory: 3.95GiB
Free memory: 3.58GiB

I tensorflow/core/common_runtime/bfc_allocator.cc:700] Sum Total of in-use chunks: 2.92GiB
I tensorflow/core/common_runtime/bfc_allocator.cc:702] Stats: 
Limit:                  3180281856
InUse:                  3140548096
MaxInUse:               3180160768
NumAllocs:                    1123
MaxAllocSize:           1250166016

----------------------------------------------------------------------------------------------------------------------------
```
W tensorflow/core/common_runtime/bfc_allocator.cc:274] ************************************************************************************xxxxxxxxxxxxxxxx
W tensorflow/core/common_runtime/bfc_allocator.cc:275] Ran out of memory trying to allocate 703.12MiB.  See logs for memory state.
```

**Comment by balancap** [comment]
@petrama Nice catch!

I finally found some time to fix the bug. 
I added to the training script a parameter `checkpoint_model_scope` where you can specify the main scope of the checkpoint file. 
I also fixed the list of ignored scope for VGG16. It's a bit long! I could change the variable scopes in the net definition to make that simpler, but I don't want to introduce any modification not backward compatible with existing checkpoints of SSD-VGG.

**Comment by RoseLii** [comment]
please help me ?
when i run
This is the eval script.
DATASET_DIR=/home/doctorimage/kindlehe/common/dataset/VOC2007/VOCtest_06-Nov-2007/VOCdevkit/VOC2007_tfrecord/
#/home/doctorimage/kindlehe/common/dataset/VOCdevkit/
#../../../../common/dataset/VOC2007/VOCtest_06-Nov-2007/VOCdevkit/
EVAL_DIR=../log_files/log_eval/ # Directory where the results are saved to
CHECKPOINT_PATH=/home/doctorimage/kindlehe/common/models/tfmodlels/SSD/VGG_VOC0712_SSD_300x300_ft_iter_120000/VGG_VOC0712_SSD_300x300_ft_iter_120000.ckpt
#../../../../common/models/tfmodlels/SSD/VGG_VOC0712_SSD_300x300_ft_iter_120000/VGG_VOC0712_SSD_300x300_ft_iter_120000.ckpt
#dataset_name这个参数在代码里面写死了
python3 ../eval_ssd_network.py 
--eval_dir=${EVAL_DIR} 
--dataset_dir=${DATASET_DIR} 
--dataset_name=pascalvoc_2007 
--dataset_split_name=test 
--model_name=ssd_300_vgg 
--checkpoint_path=${CHECKPOINT_PATH} 
--batch_size=1
raise ValueError('No data files found in %s' % (data_sources,))
ValueError: No data files found in /home/y/2T/wangxingli/SSD-Tensorflow/shujuji/VOCtrainval_06-Nov-2007/VOCdevkit/VOC2007/voc_2007_test_*.tfrecord
but i DATASET_DIR is my datasets path,why error
