### ISSUE TITLE
how to split voc2007 to train and test tfcord

### ISSUE THREAD

**Issue by duanLH** [balancap/SSD-Tensorflow#18]
In pascalvoc_2007.py, there is a function named get split,but I dont know how to use it to split the dataset. thanks.

**Comment by changingivan** [comment]
You need to split the dataset manually, e.g. using a python script, according to the trainval.txt and test.txt in VOC2007/ImageSets/Main/ .

**Comment by changingivan** [comment]
@duanLH You need to split the dataset manually, e.g. using a python script, according to the trainval.txt and test.txt in VOC2007/ImageSets/Main/ .

**Comment by duanLH** [comment]
@changingivan  I think the code can split automatically

**Comment by balancap** [comment]
The dataset needs to be split into different files at the conversion stage. The Pascal VOC 2007 has two different zip files, one for training and one for testing, and you can run the script on both two get the two splitted TFRecords datasets.
The `split_name` parameter is just here for matching filenames from training or testing files.
