### ISSUE TITLE
fine tune from original vgg model（vgg_16.ckpt)

### ISSUE THREAD

**Issue by duanLH** [balancap/SSD-Tensorflow#19]
when I finetune from vgg_16.ckpt, error with ：Tensor name "ssd_300_vgg/conv2/conv2_2/biases" not found in checkpoint files ./vggmodel/vgg_16.ckpt.
how to solve this problem .thanks

**Comment by yyjFish** [comment]
I was having a same problem, then I used inspect_checkpoint.py script (https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/tools/inspect_checkpoint.py) to inspect it.

Also I realized there is inconsistency with names.

I added this in tf_utils.py in function get_init_function right after for loop

```
def name_in_checkpoint(var):
    if 'ssd_300_vgg' in var.op.name:
         return var.op.name.replace('ssd_300_vgg','vgg_16')
variables_to_restore = {name_in_checkpoint(var): var for var in variables_to_restore}
```

My script for training is like this:
```

DATASET_DIR=/home/pmarce/datasets/VOCdevkit/tfrecords
TRAIN_DIR=./logs/
CHECKPOINT_PATH=./checkpoints/vgg_16.ckpt
python3 train_ssd_network.py
--train_dir=${TRAIN_DIR}
--dataset_dir=${DATASET_DIR}
--dataset_name=pascalvoc_2007
--dataset_split_name=train
--model_name=ssd_300_vgg
--checkpoint_path=${CHECKPOINT_PATH}
--checkpoint_exclude_scopes=ssd_300_vgg/block4_box,ssd_300_vgg/block7_box,ssd_300_vgg/block8_box,ssd_300_vgg/block9_box,ssd_300_vgg/block10_box,ssd_300_vgg/block11_box,ssd_300_vgg/block8,ssd_300_vgg/block9,ssd_300_vgg/block10,ssd_300_vgg/block11,ssd_300_vgg/conv6,ssd_300_vgg/conv7
--save_summaries_secs=60
--save_summaries_secs=60
--save_interval_secs=600
--weight_decay=0.00001
--optimizer=adam
--learning_rate=0.0001
--batch_size=8
```

**Comment by yyjFish** [comment]
当我按照上面的步骤处理，别的问题没有了。。。但是貌似他这个程序非常非常吃显存

我用的泰坦服务器  12G显存   都提示显存不够   无法运行，，，  我觉得程序还有很多很多问题啊

**Comment by duanLH** [comment]
@yyjFish thanks, it's running now, I also use tatian , maybe you should change 'gpu_memory_fraction' to 0.9

**Comment by miraclebiu** [comment]
What is your training time guys? On my K80, the training process is very slow， and I don't know why
