### ISSUE TITLE
How much annotation information does this network need?

### ISSUE THREAD

**Issue by S-aiueo32** [balancap/SSD-Tensorflow#196]
Hi.
I could train and test on VOC2007 well.
Thank you for this work.

As the next step, I want to train on my own data.
I will make XML files along the format of VOC2007.
In the object detection, I think the information of `<name>` and `<bndbox>` is only needed.
But VOC2007 has other information like `<source>`, `<segmented>`, `<truncated>` and so on.
Does this network needs the others?

**Comment by Cuky88** [comment]
No it doesn't need the other information, only images, classes and bounding boxes.

**Comment by S-aiueo32** [comment]
Thanks a lot!
I have been able to run `train_ssd_network.py`. As a training, it may works well.
My dataset has different number of classes from VOC so I have some changes to fit like below.

- `VOC_LABELS ` in `pascalvoc_common.py`
- `NUMCLASSES` in `pascalvoc_2007.py`
- Giving the argument `--num_classes` fitting my own dataset

Do I need to changes more, or not?

In addition, I have another restoring problem caused by num_classes difference.
If anyone has advice, please help me.
I will throw a new issue after my considering...

**Comment by Cuky88** [comment]
You need to change number of classes in the SSD parameters, too. There you have to set number of your class + 1 for background.

**Comment by S-aiueo32** [comment]
> You need to change number of classes in the SSD parameters, too.

I'm sorry but I don't know where to fix to change the parameters.
Do you want me to fix all the number `21` searched in this repository to `12` (my dataset has 11 classes) for the moment?

**Comment by S-aiueo32** [comment]
I could train and restore. Thank you.

**Comment by Janezzliu** [comment]
Hi,@S-aiueo32 ,Could please tell me how to change TRAIN_STATISTICS and  TEST_STATISTICS in pascalvoc_2007.py?The original is as follows:
TRAIN_STATISTICS = {
    'none': (0, 0),
    'aeroplane': (238, 306),
    'bicycle': (243, 353),
    'bird': (330, 486),
    'boat': (181, 290),
    'bottle': (244, 505),
    'bus': (186, 229),
    'car': (713, 1250),
    'cat': (337, 376),
    'chair': (445, 798),
    'cow': (141, 259),
    'diningtable': (200, 215),
    'dog': (421, 510),
    'horse': (287, 362),
    'motorbike': (245, 339),
    'person': (2008, 4690),
    'pottedplant': (245, 514),
    'sheep': (96, 257),
    'sofa': (229, 248),
    'train': (261, 297),
    'tvmonitor': (256, 324),
    'total': (5011, 12608),
}
TEST_STATISTICS = {
    'none': (0, 0),
    'aeroplane': (1, 1),
    'bicycle': (1, 1),
    'bird': (1, 1),
    'boat': (1, 1),
    'bottle': (1, 1),
    'bus': (1, 1),
    'car': (1, 1),
    'cat': (1, 1),
    'chair': (1, 1),
    'cow': (1, 1),
    'diningtable': (1, 1),
    'dog': (1, 1),
    'horse': (1, 1),
    'motorbike': (1, 1),
    'person': (1, 1),
    'pottedplant': (1, 1),
    'sheep': (1, 1),
    'sofa': (1, 1),
    'train': (1, 1),
    'tvmonitor': (1, 1),
    'total': (20, 20),
}
SPLITS_TO_SIZES = {
    'train': 5011,
    'test': 4952,
}
SPLITS_TO_STATISTICS = {
    'train': TRAIN_STATISTICS,
    'test': TEST_STATISTICS,
}
NUM_CLASSES = 20




Because of I don't know the meaning of 238, 306 in 'aeroplane': (238, 306),so I don't know how to change it.Could please give me a favour?Thanks a lot!
