### ISSUE TITLE
Train Imagenet Training Data

### ISSUE THREAD

**Issue by hongym7** [balancap/SSD-Tensorflow#197]
I want to train by using a imagenet training data.
so, num_classes parameter value change to 1001 from 21.

but, i saw below error.
maybe 
4004 is 1001 x 4.
84 is 21 x 4

give me a information.

InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [4004] rhs shape= [84]
	 [[Node: save/Assign_15 = Assign[T=DT_FLOAT, _class=["loc:@ssd_300_vgg/block10_box/conv_cls/biases"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](ssd_300_vgg/block10_box/conv_cls/biases, save/RestoreV2_15)]]

**Comment by speculaas** [comment]
Dear Hongym7,
Thanks for your help!
Can your share how you overcome this error?
BR,
JimmyYS
