### ISSUE TITLE
Change base models to new tensorflow layers

### ISSUE THREAD

**Issue by leonardoaraujosantos** [balancap/SSD-Tensorflow#2]
Hi @balancap nice job thanks for releasing this implementation.

What you think about changing the base networks implementation to use the new tf.layers [VGG](https://github.com/balancap/SSD-Tensorflow/blob/master/nets/vgg.py)

I'm learn this watching the videos from the tensorflow summit
https://youtu.be/t64ortpgS-E?t=433

**Comment by balancap** [comment]
Thanks :)

In short, yes I'll try to switch as much as possible to the new api in TF 1.0.

If you want the long version : TF Slim is basically the old name of this new API :) More precisely, TF slim has always been (with a few nice additional tools for dataset management and training loops) a namespace for the functionalities available in tf.contrib.layers / metrics / losses. With TF 1.0, Google decided to move the stable parts of tf.contrib to the official API to have a Keras-like light functional API, hence leading to tf.layers, tf.metrics and tf.losses. So basically, switching to the latter is a simply change of method name :) (and maybe a few slightly different argument).

**Comment by leonardoaraujosantos** [comment]
Cool @balancap also thanks for the feedback. I'm also studying about SSD by having long discussions with @weiliu89
[Filter with all our talks](https://github.com/weiliu89/caffe/issues/created_by/leonardoaraujosantos)

I'm working on a Deep Learning library kind of from scratch by watching courses like cs231n, but with Matlab and OpenCL.
https://github.com/leonardoaraujosantos/DLMatFramework

**Comment by balancap** [comment]
My implementation is far from being as complete as @weiliu89 one :)
Basic usage of the SSD should be fine, but I am still working on improving the evaluation and training script. Once this is done, it should hopefully be easy to try new architectures.
