### ISSUE TITLE
Error: Variables not initialized when trying to evaluate on VOC 07

### ISSUE THREAD

**Issue by UndecidedBoy** [balancap/SSD-Tensorflow#304]
Hello,

I'm trying this code on windows 10 with python 3.6 and Tensorflow 1.12.

While trying to evaluate SSD on Pascal VOC 2007, i'm getting the following error:
`RuntimeError: Init operations did not make model ready for local_init.`

This comes from the following function:
```
slim.evaluation.evaluate_once(
                master=FLAGS.master,
                checkpoint_path=checkpoint_path,
                logdir=FLAGS.eval_dir,
                num_evals=num_batches,
                eval_op=flatten(list(names_to_updates.values())),
                variables_to_restore=variables_to_restore,
                session_config=config)
```
I presume that there is a new input in the function for the initialization process, but I can't get a grasp on what to feed it with, or if one input is deprecated and there is a new name for it.

Every help is appreciated!
Thanks in advance :)

**Comment by jianyuheng** [comment]
I got the same problem, have you solved it?

**Comment by UndecidedBoy** [comment]
Hi,
No I did not manage yet to find what the reason behind this error is.

**Comment by wangxianrui** [comment]
I got the same problem also...

**Comment by UndecidedBoy** [comment]
I thought that initializing with an intial_op in the function would do the trick, but it did not...

**Comment by jianyuheng** [comment]
@UndecidedBoy @wangxianrui 
I think I found a solution to the problem.
`SSD-Tensorflow-master\tf_extended\metrics.py", line 51, in _create_local  tf.Variable()`

`
 return variables.Variable(
            initial_value=array_ops.zeros(shape, dtype=dtype),
            name=name,
            trainable=False,
            collections=collections,
            validate_shape=validate_shape)`

The problem is that we did not initialize local variables created by `slim.metrics`.

Two ways to solve this problem  ：

1. use `variables.Variable._variable_v1_call()`
2. or you can choose the way to downgrade tensorflow version to 1.6.0

**Comment by B3QL** [comment]
> 1. use `variables.Variable._variable_v1_call()`

Changing L51 in `tf_extended\metrics.py` to `variables.VariableV1(...)` fixes it.

**Comment by TaehoLi** [comment]
I fix this error by above one, thx!!
(TypeError: _variable_v2_call() got an unexpected keyword argument 'collections')
