### ISSUE TITLE
feat_ymin = tf.zeros while feat_ymax = tf.ones

### ISSUE THREAD

**Issue by bysowhat** [balancap/SSD-Tensorflow#31]
codes of function "tf_ssd_bboxes_encode_layer"
   feat_ymin = tf.zeros(shape, dtype=dtype)
    feat_xmin = tf.zeros(shape, dtype=dtype)
    feat_ymax = tf.ones(shape, dtype=dtype)
    feat_xmax = tf.ones(shape, dtype=dtype)

why fest_ymin is tf.zeros but the feat_ymax is tf.ones?

**Comment by balancap** [comment]
The idea is just to initialize every box coordinates to `(0, 0, 1, 1)`.

**Comment by bysowhat** [comment]
thanks a lot!
