### ISSUE TITLE
'module' object has no attribute 'plasma'

### ISSUE THREAD

**Issue by ljdang** [balancap/SSD-Tensorflow#32]
I have a problem when testing ssd_notebook. It seems that matplotlib.cm has no attribute 'plasma'.

**Comment by balancap** [comment]
You may need the new Matplotlib 2.0. Otherwise, I was just using this `plasma` for colors selection, so you can just comment this line.

**Comment by ljdang** [comment]
@balancap I fix it. Thanks!
