### ISSUE TITLE
SSD能训练png图片，但不能测试png图片吗？

### ISSUE THREAD

**Issue by dongzi19941026** [balancap/SSD-Tensorflow#377]

**Comment by dongzi19941026** [comment]
like this :ValueError: Cannot feed value of shape (480, 640) for Tensor 'Placeholder:0', which has shape '(?, ?, 3)'

**Comment by life334** [comment]
请问，这个问题解决了吗？怎么解决的？

**Comment by dongzi19941026** [comment]
你可以把png图片专业jpg图片。



---原始邮件---
发件人: "life"<notifications@github.com&gt;
发送时间: 2020年7月16日(周四) 下午4:35
收件人: "balancap/SSD-Tensorflow"<SSD-Tensorflow@noreply.github.com&gt;;
抄送: "State change"<state_change@noreply.github.com&gt;;"dongzi19941026"<1550842779@qq.com&gt;;
主题: Re: [balancap/SSD-Tensorflow] SSD能训练png图片，但不能测试png图片吗？ (#377)




 
请问，这个问题解决了吗？怎么解决的？

**Comment by life334** [comment]
我的图片本身就是jpg格式的。我解决的方式是：增加一步 cv2.cvtColor(img, cv2.COLOR_GRAY2RGB) 就好了
