### ISSUE TITLE
How to run a single image detection

### ISSUE THREAD

**Issue by Goldjin** [balancap/SSD-Tensorflow#5]
We have run your eval_ssd_network.py in Command.md  and successfully get a eval/precision score. We want to run a single image detection and get a new image just like ex1.png. Could you help us to run it ? Your ssd_tests.ipynb in notebook is not very clear for this purpose. Thanks.

**Comment by balancap** [comment]
Did you try the notebook `ssd_notebook.ipynb`? The former should be much cleaner and simpler than the test notebook :)
