### ISSUE TITLE
is there any way to visualise the SSD structure

### ISSUE THREAD

**Issue by gaopeng-eugene** [balancap/SSD-Tensorflow#54]

**Comment by xaibeing** [comment]
Tensorboard can show the Graph.
In simple way, just add "tf.summary.FileWriter" like this:

```
# Restore SSD model.
ckpt_filename = '../checkpoints/ssd_300_vgg.ckpt'
isess.run(tf.global_variables_initializer())

# create tensorboard file under dir "tensorboard"
writer =  tf.summary.FileWriter("tensorboard", isess.graph)
```

Then, in command line terminal start tensorboard like:
`tensorboard --logdir ./tensorboard`

finally open a browser and navigate to "http://localhost:6006/", or follow the instruction in the "tensorboard" commad. When page shows, the "GRAPH" gives the whole SSD structure.

**Comment by balancap** [comment]
As @xaibeing points it out, the best way is to use Tensorboard for visualizing the graph. You will get all the information you may want with this tool.

Thanks @xaibeing for the snippet! Was not aware of this trick to save the tensorboard files :)
Another way is to launch the training script, and just stop it once the first iteration is done. The checkpoint generated contains all the graph information as well.
