### ISSUE TITLE
typo reminder for 'gpu_memory_fraction'

### ISSUE THREAD

**Issue by jamescfli** [balancap/SSD-Tensorflow#56]
Hi @balancap 

Just a kind reminder that in your [train ssd example](https://github.com/balancap/SSD-Tensorflow/blob/master/train_ssd_network.py), it should be DEFINE_float rather than integer in Line 63.

> tf.app.flags.DEFINE_integer(
>        'gpu_memory_fraction', 0.75, 'GPU memory fraction to use.')

**Comment by balancap** [comment]
Thanks for spotting the mistake. Fixed!
