### ISSUE TITLE
about the matching strategy:jaccard overlap higher than a threshold(0.5)

### ISSUE THREAD

**Issue by chenweiqian** [balancap/SSD-Tensorflow#71]
in tf_ssd_bboxes_encode_layer.body:
 `      jaccard = jaccard_with_anchors(bbox)
        # Mask: check threshold + scores + no annotations + num_classes.
        mask = tf.greater(jaccard, feat_scores)
        # mask = tf.logical_and(mask, tf.greater(jaccard, matching_threshold))
        mask = tf.logical_and(mask, feat_scores > -0.5)
        mask = tf.logical_and(mask, label < num_classes)
        imask = tf.cast(mask, tf.int64)
        fmask = tf.cast(mask, dtype)`

why not is 0.5?

**Comment by SunAriesCN** [comment]
I think the -0.5 here doesn't infer the jaccard overlap threshold to get the default boxes, it's just a protecting process. And the jaccard overlap threshold is in the ssd_losses function which on ssd_vgg_300.py, and you would see it before the pmask present.

**Comment by chenweiqian** [comment]
thank you!
