### ISSUE TITLE
how to make it run on android?

### ISSUE THREAD

**Issue by chenweiqian** [balancap/SSD-Tensorflow#74]
i want to run it on android. But i have tried failed. Anyone who can help!! Thanks!!

**Comment by JcmeLs** [comment]
@chenweiqian Use java api or c++ api?

**Comment by chenweiqian** [comment]
@JcmeLs Thanks for your replying！ I have already succeeded。

**Comment by KindleHe** [comment]
@chenweiqian  Could you share some tips or tutorials on how to run ssd-tensorflow on Android?

**Comment by chenweiqian** [comment]
I sort out this aspect. The link is as follows：http://m.blog.csdn.net/chenweiqian_zy/article/details/75040273
