### ISSUE TITLE
Checkpoint load failure

### ISSUE THREAD

**Issue by eslamahmedkhair** [balancap/SSD-Tensorflow#99]
So I get this error when executing **ssd_notebook.ipynb** :

DataLossError: Unable to open table file ../checkpoints/ssd_300_vgg.ckpt: Failed precondition: ../checkpoints/ssd_300_vgg.ckpt: perhaps your file is in a different file format and you need to use a different restore operator?

Also tried this path '../checkpoints/ssd_300_vgg.ckpt/ssd_300_vgg.ckpt.data-00000-of-00001'

but it gives me the same error, any hint?

**Comment by skalinin** [comment]
I have the same error. Can anyone help, please?

**Comment by skalinin** [comment]
I've just solved it by changing the path from
ckpt_filename ='/Users/kalinin/desktop/log/model.ckpt-60807.data-00000-of-00001'
to
ckpt_filename ='/Users/kalinin/desktop/log/model.ckpt-60807'

don't know why but it works

**Comment by eslamahmedkhair** [comment]
OK, so I used this instead '../checkpoints/ssd_300_vgg.ckpt.data'

but now am getting this : Unsuccessful TensorSliceReader constructor: Failed to get matching files on ../checkpoints/sasd/ssd_300_vgg.ckpt.data-00000-of-00001: Not found: ../checkpoints/sasd

Thanks in advance

**Comment by pierre-ecarlat** [comment]
Tensorflow expects the path to the checkpoint, not to the data, so you should try: '../checkpoints/ssd_300_vgg.ckpt' instead. It doesn't point to any file, but tensorflow will use it to find everything it needs to restore the data.

**Comment by eslamahmedkhair** [comment]
Thanks to you I was able to execute that piece of code.

I happen to have another issue while reading an image using matplotlib, The following link illustrates the problem [here](https://stackoverflow.com/questions/43943616/error-attempting-to-open-image-with-matplotlib-image), any clues?

This is the traceback just in case:
`AttributeError                            Traceback (most recent call last)
<ipython-input-8-376fd4670125> in <module>()
      4 print path + image_names[0]
      5 
----> 6 img = mpimg.imread(path + image_names[0])
      7 rclasses, rscores, rbboxes =  process_image(img)
      8 

/home/eslam/miniconda2/lib/python2.7/site-packages/matplotlib/image.pyc in imread(fname, format)
   1276 
   1277     if ext not in handlers:
-> 1278         im = pilread(fname)
   1279         if im is None:
   1280             raise ValueError('Only know how to handle extensions: %s; '

/home/eslam/miniconda2/lib/python2.7/site-packages/matplotlib/image.pyc in pilread(fname)
   1254         except ImportError:
   1255             return None
-> 1256         with Image.open(fname) as image:
   1257             return pil_to_array(image)
   1258 

/home/eslam/miniconda2/lib/python2.7/site-packages/PIL/Image.pyc in __getattr__(self, name)
    510             new['data'] = self.tostring()
    511             return new
--> 512         raise AttributeError(name)
    513 
    514     ##`

**Comment by eslamahmedkhair** [comment]
Well after some digging, installing pillow will solve that error using conda that would be:
conda install pillow

though I really dunno why it got solve! but Thanks For your help gents!

**Comment by CODEJY** [comment]
I met this error too, but I can't solve it by your way.
my code
![2017-10-18 16 49 54](https://user-images.githubusercontent.com/14768204/31709397-78d76600-b424-11e7-924a-bc951d9dd065.png)
my folder
![2017-10-18 16 51 12](https://user-images.githubusercontent.com/14768204/31709423-94b4c412-b424-11e7-85e8-ee6b99c4bd7b.png)

**Comment by saurabheights** [comment]
@CODEJY and anyone facing this issue later - Move the ssd_300_vgg files into checkpoints folder.
